# frozen_string_literal: true

class Kana < ActiveHash::Base # :nodoc:
  self.data = [
    { id: 1, name: 'あ' },
    { id: 2, name: 'い' },
    { id: 3, name: 'う' },
    { id: 4, name: 'え' },
    { id: 5, name: 'お' },
    { id: 6, name: 'か' },
    { id: 7, name: 'き' },
    { id: 8, name: 'く' },
    { id: 9, name: 'け' },
    { id: 10, name: 'こ' },
    { id: 11, name: 'さ' },
    { id: 12, name: 'し' },
    { id: 13, name: 'す' },
    { id: 14, name: 'せ' },
    { id: 15, name: 'そ' },
    { id: 16, name: 'た' },
    { id: 17, name: 'ち' },
    { id: 18, name: 'つ' },
    { id: 19, name: 'て' },
    { id: 20, name: 'と' },
    { id: 21, name: 'な' },
    { id: 22, name: 'に' },
    { id: 23, name: 'ぬ' },
    { id: 24, name: 'ね' },
    { id: 25, name: 'の' },
    { id: 26, name: 'は' },
    { id: 27, name: 'ひ' },
    { id: 28, name: 'ふ' },
    { id: 29, name: 'へ' },
    { id: 30, name: 'ほ' },
    { id: 31, name: 'ま' },
    { id: 32, name: 'み' },
    { id: 33, name: 'む' },
    { id: 34, name: 'め' },
    { id: 35, name: 'も' },
    { id: 36, name: 'や' },
    { id: 37, name: 'ゆ' },
    { id: 38, name: 'よ' },
    { id: 39, name: 'ら' },
    { id: 40, name: 'り' },
    { id: 41, name: 'る' },
    { id: 42, name: 'れ' },
    { id: 43, name: 'ろ' },
    { id: 44, name: 'わ' },
    { id: 45, name: 'を' },
    { id: 46, name: 'ん' },
    { id: 47, name: 'A' },
    { id: 48, name: 'B' },
    { id: 49, name: 'C' },
    { id: 50, name: 'D' },
    { id: 51, name: 'E' },
    { id: 52, name: 'F' },
    { id: 53, name: 'G' },
    { id: 54, name: 'H' },
    { id: 55, name: 'I' },
    { id: 56, name: 'J' },
    { id: 57, name: 'K' },
    { id: 58, name: 'L' },
    { id: 59, name: 'M' },
    { id: 60, name: 'N' },
    { id: 61, name: 'O' },
    { id: 62, name: 'P' },
    { id: 63, name: 'Q' },
    { id: 64, name: 'R' },
    { id: 65, name: 'S' },
    { id: 66, name: 'T' },
    { id: 67, name: 'U' },
    { id: 68, name: 'V' },
    { id: 69, name: 'W' },
    { id: 70, name: 'X' },
    { id: 71, name: 'Y' },
    { id: 72, name: 'Z' },
    { id: 73, name: '1' },
    { id: 74, name: '2' },
    { id: 75, name: '3' },
    { id: 76, name: '4' },
    { id: 77, name: '5' },
    { id: 78, name: '6' },
    { id: 79, name: '7' },
    { id: 80, name: '8' },
    { id: 81, name: '9' },
    { id: 82, name: '0' },
    { id: 99, name: '他' }
  ]

  class << self
    def ids
      all.map(&:id)
    end
  end
end
